from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
import sys
import os

# Add parent directory to path to ensure proper imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import models
from database import get_db

router = APIRouter(tags=["Insights"])


@router.get("/insights")
def get_latest_insights(db: Session = Depends(get_db)):
    """
    Returns the latest user profile insights generated by the background intelligence loop.
    """
    try:
        insight = db.query(models.Insight).order_by(models.Insight.created_at.desc()).first()
        if not insight:
            return {
                "summary": "No insights available yet. Please add more webpage memories to trigger analysis.",
                "created_at": None
            }
        return {
            "summary": insight.summary,
            "created_at": insight.created_at
        }
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to fetch insights: {str(e)}"
        )
